In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### Step-1: Load the data

In [3]:
df = pd.read_csv(r"C:\Users\Ajay kumar\OneDrive\Documents\Innomatics\M5-Machine Learning\TASKS\TASK_5\diamonds.csv")
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
df.isnull().sum()
df.shape

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

(53940, 10)

In [5]:
df.duplicated().sum()

146

In [6]:
df.drop_duplicates(inplace=True)
df.shape

(53794, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53794 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53794 non-null  float64
 1   cut      53794 non-null  object
 2   color    53794 non-null  object
 3   clarity  53794 non-null  object
 4   depth    53794 non-null  float64
 5   table    53794 non-null  float64
 6   price    53794 non-null  int64
 7   x        53794 non-null  float64
 8   y        53794 non-null  float64
 9   z        53794 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.5+ MB

In [8]:
df.describe()

,carat,depth,table,price,x,y,z
count,53794.00000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000
mean,0.79778,61.748080,57.458109,3933.065082,5.731214,5.734653,3.538714
std,0.47339,1.429909,2.233679,3988.114460,1.120695,1.141209,0.705037
min,0.20000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.40000,61.000000,56.000000,951.000000,4.710000,4.720000,2.910000
50%,0.70000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.04000,62.500000,59.000000,5326.750000,6.540000,6.540000,4.030000
max,5.01000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

### Step-2: Identify input and output variables

In [12]:
X=df.drop(columns={'price'})
X.shape

(53794, 9)

In [13]:
y=df['price']
y.shape

(53794,)

### Step-3: Split the data - Test and Train (recommended 75:25 split)

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((40345, 9), (13449, 9), (40345,), (13449,))

In [17]:
X_train

       carat        cut color clarity  depth  table     x     y     z
12820   1.02      Ideal     G     VS2   62.4   57.0  6.47  6.36  4.00
19997   1.05  Very Good     F    VVS2   61.3   59.0  6.48  6.56  4.00
6099    0.91    Premium     G     SI1   62.6   58.0  6.17  6.14  3.85
37984   0.32      Ideal     D    VVS2   60.9   57.0  4.39  4.45  2.70
24865   1.52    Premium     G     VS2   61.9   56.0  7.39  7.28  4.54
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
11311   1.00    Premium     H     VS2   60.4   58.0  6.51  6.46  3.92
44869   0.63      Ideal     G     SI1   61.7   54.0  5.52  5.56  3.42
38271   0.32      Ideal     J     SI1   61.8   54.9  4.39  4.42  2.72
860     0.90    Premium     J     SI1   62.8   59.0  6.13  6.03  3.82
15832   1.01    Premium     G     VS1   62.7   58.0  6.36  6.31  3.97

[40345 rows x 9 columns]

### Step-4: Data Preprocessing

In [18]:
df['cut'].unique()
df['clarity'].unique()
df['color'].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

array(['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF'],
      dtype=object)

array(['E', 'I', 'J', 'H', 'F', 'G', 'D'], dtype=object)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler

In [20]:
ordinal_cols = ['cut', 'clarity', 'color']

In [21]:
cut_order = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
clarity_order = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']
color_order = ['J', 'I', 'H', 'G', 'F', 'E', 'D']

In [22]:
oe = OrdinalEncoder(categories=[cut_order,clarity_order,color_order])
oe

OrdinalEncoder(categories=[['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'],
                           ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1',
                            'IF'],
                           ['J', 'I', 'H', 'G', 'F', 'E', 'D']])

In [23]:
num_cols = ['carat', 'depth', 'table', 'x', 'y', 'z']

In [24]:
min_max=MinMaxScaler()
min_max

MinMaxScaler()

#### Categorical Data Encoding and Numerical Data Rescaling on X_train

In [25]:
ct = ColumnTransformer(transformers=[('ordinal', oe, ordinal_cols),('scaler', MinMaxScaler(), num_cols)]
                       ,remainder='passthrough',verbose_feature_names_out=False).set_output(transform='pandas')

In [26]:
X_train_transformed = ct.fit_transform(X_train)
X_train_transformed.head()

,cut,clarity,color,carat,depth,table,x,y,z
12820,4.0,3.0,3.0,0.170478,0.538889,0.269231,0.602421,0.107980,0.496278
19997,2.0,5.0,4.0,0.176715,0.508333,0.307692,0.603352,0.111375,0.496278
6099,3.0,2.0,3.0,0.147609,0.544444,0.288462,0.574488,0.104244,0.477667
37984,4.0,5.0,6.0,0.024948,0.497222,0.269231,0.408752,0.075552,0.334988
24865,3.0,3.0,3.0,0.274428,0.525000,0.250000,0.688082,0.123599,0.563275

#### Categorical Data Encoding and Numerical Data Rescaling on x_test

In [27]:
ordinal_cols = ['cut', 'clarity', 'color']

In [28]:
cut_order = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
clarity_order = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']
color_order = ['J', 'I', 'H', 'G', 'F', 'E', 'D']

In [29]:
oe = OrdinalEncoder(categories=[cut_order,clarity_order,color_order])
oe

OrdinalEncoder(categories=[['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'],
                           ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1',
                            'IF'],
                           ['J', 'I', 'H', 'G', 'F', 'E', 'D']])

In [30]:
num_cols = ['carat', 'depth', 'table', 'x', 'y', 'z']

In [31]:
min_max=MinMaxScaler()
min_max

MinMaxScaler()

In [32]:
ct1 = ColumnTransformer(transformers=[('ordinal', oe, ordinal_cols),('scaler', MinMaxScaler(), num_cols)]
                       ,remainder='passthrough',verbose_feature_names_out=False).set_output(transform='pandas')

In [33]:
X_test_transformed = ct1.fit_transform(X_test)
X_test_transformed.head()

,cut,clarity,color,carat,depth,table,x,y,z
43657,0.0,3.0,0.0,0.146974,0.750000,0.166667,0.570994,0.563710,0.113836
4274,2.0,1.0,5.0,0.201729,0.616438,0.333333,0.622718,0.629969,0.118239
47412,4.0,4.0,3.0,0.106628,0.654110,0.233333,0.537525,0.543323,0.103774
44437,3.0,3.0,5.0,0.089337,0.667808,0.366667,0.515213,0.519878,0.100000
13975,4.0,2.0,1.0,0.285303,0.660959,0.200000,0.689655,0.695209,0.133333

In [34]:
X_train_transformed

,cut,clarity,color,carat,depth,table,x,y,z
12820,4.0,3.0,3.0,0.170478,0.538889,0.269231,0.602421,0.107980,0.496278
19997,2.0,5.0,4.0,0.176715,0.508333,0.307692,0.603352,0.111375,0.496278
6099,3.0,2.0,3.0,0.147609,0.544444,0.288462,0.574488,0.104244,0.477667
37984,4.0,5.0,6.0,0.024948,0.497222,0.269231,0.408752,0.075552,0.334988
24865,3.0,3.0,3.0,0.274428,0.525000,0.250000,0.688082,0.123599,0.563275
...,...,...,...,...,...,...,...,...,...
11311,3.0,3.0,2.0,0.166320,0.483333,0.288462,0.606145,0.109677,0.486352
44869,4.0,2.0,3.0,0.089397,0.519444,0.211538,0.513966,0.094397,0.424318
38271,4.0,2.0,0.0,0.024948,0.522222,0.228846,0.408752,0.075042,0.337469
860,3.0,2.0,0.0,0.145530,0.550000,0.307692,0.570764,0.102377,0.473945
15832,3.0,4.0,3.0,0.168399,0.547222,0.288462,0.592179,0.107131,0.492556

### Step 6: KNN Regressor(From Scratch)

In [36]:
X_train_arr=np.array(X_train_transformed)
X_test_arr=np.array(X_test_transformed)
y_train_arr=np.array(y_train)

In [37]:
# Distance calculation

def distance_from_all_train(X_train_arr, one_test_row):
    # Euclidean distance
    return np.sqrt(np.sum((X_train_arr - one_test_row)**2, axis=1))

In [38]:
# Predict 1 row
def predict_one(X_train_arr, y_train_arr, one_test_row, k):
    d = distance_from_all_train(X_train_arr, one_test_row)
    nearest_k_index = np.argsort(d)[:k]
    return np.mean(y_train_arr[nearest_k_index])

In [39]:
# Predict all test rows
def predict_all(X_train_arr, y_train_arr, X_test_arr, k):
    preds = []
    for i in range(len(X_test_arr)):
        preds.append(predict_one(X_train_arr, y_train_arr, X_test_arr[i], k))
    return np.array(preds)

In [41]:
X_train_small = X_train_arr[:5000]   # limited x_train data only to 5000 observations
y_train_small = y_train_arr[:5000]   # limited y_train data only to 5000 observations
X_test_small  = X_test_arr[:500]     # limited x_test data only to 500 observations

k = 5

y_pred_scratch = predict_all(X_train_small, y_train_small, X_test_small, k)
y_pred_scratch

array([ 4437.4,  2087.2,  1237.2,  1128.6,  4756.8,   597.4,   675.6,
        1330.6,  1186. ,  4098. ,  1685. ,  4121.6,  4534.6,   628. ,
        1984. ,  5235. ,  2586. ,  5235. ,  2668.8,   904.8,  2133.8,
        2687.2,  3641.6,  2155.6,   635.2,  3790.8,   597.8,  3418.8,
        9173.4,  1953. ,  6213. ,  2702.8,   528.4,   846.4,   798.6,
        1066.2,  3792. ,  1020.8,  1093.4,  6352.6,   795.2,  1026.6,
         494. ,  1606.4,  3992. ,  4735.2,  1510.6,   757.8,  1590.6,
        1618.8,   929.4,  1401.6,   634.6,   632.2,   592.2,  5497.2,
         682.2, 15080. ,   966.2,  1176.8,  3952.2,  4318.8,  4803.4,
        1040.2,  2938.8,  2431.4,  8868. ,   797.2, 12692.6,  6797.8,
        3954.4,   834.6,  4254.2,  3239.2,  1948.8,  5127.8,  3996.4,
         920.8,  2422.6,   939.8,  1433.4,  1698.2,  1926. ,  1273. ,
        6194.8,  1466.8,  1780.2,  4997.4,   584.8,   992.4,  8655.2,
        1222.8,  3514. ,  5235. ,   874.8,   466.6,   592.6,  2528. ,
       12486.6,   837.8,   930. ,  2485.6,  1841.8,  4015. ,  1087. ,
         672.2,   690.4,   516. ,   834.6,  8697.8,  3707. ,  7707.8,
       13831.2,  5261.8,   511.8,  5402.2,  1561.6,   625.6,   479. ,
        1940.4,  1195.8,   642.2, 15323.6,  1307. ,   721.8,  5473.8,
        3911.6,  1585. ,   742.2,  7412.8,  2470.8,  2457.4,   670.2,
        2252.8,   666.8,  3401.8,   807.4,  2505.2,   817. ,   909.8,
         997.4,  1275.2,   659.4,  4995.4,  1964.2,  1191.4,  4562. ,
         587.6,  3824.2,   775. ,  5390.2,  6090.2,   716.6,   587.6,
         871.6,  6682.6,   771.4,  3045.6,  1586.6,  5294.2,   847.8,
         944. ,   838.8,   839. ,  2865.8,  3726.2,  4201.8,  3518.4,
        2845.2,  3268.8,   622.6,   855.6,  5341.2,   590.6,  4297.6,
        2940.6,  4201.8,   784. ,  5097.8,  4490.4,  1183. , 14840.2,
        6989. ,  2175. ,  4143.2,  3911.6,  1176.8,   687.6,   741. ,
         676.8,   955.6,   604.2,  4219.4,   572.2,  4142.6,  3708.2,
        1191. ,  8680. ,  1020.8,  4956.4, 15588.4,  2813.6,  4824. ,
        1662.8,   625.6,  5332.4,   658. ,  1228.4,  2984.2,   644.6,
         853.8,  1259. ,   829.2,  1645.2,  5650.4,  7387.6, 12486.6,
         676.2,  4318.4,   632.2,  4161.6,  1768.8,   849.8,  4993.8,
         874. ,   731.2,  4723. ,   494. ,   674.6,   889. ,   790.8,
       11342.8,  4346.8, 13681.4,  4669.4,  6941. ,  5091.6,  4651.8,
        5645.8,  9502.8,  7946.8,   922.8,   784. ,  1066.8,   933.4,
        1302.4,   609.2,   603.2,  1349.6,  1755.8,  4515.8,   728.8,
        1790. ,  4454.4,   798.6,   676.8,  3325.4,   597.8,  2907.8,
         960.8,   826.8,   774.6,  4726. ,  1399.6,  8217.2,  1510.6,
        9272.8,  3789.6,  4523.2,   861. ,  3746.6,   748.4,  2009.8,
        1387. ,  4048. ,   635.2,   688.8,   605.4,   726.6,  8386.8,
         731.2,  1075.8,   749.8,  4890.6,  5029.8,   830.8,   826.8,
        5478.6,   513.6,  4283. ,  3530.2,  3952.2,  8305.6,   853.8,
       10462.2,   808.6,  1082.8,   658. ,  5505. ,  1810.2,  1548.8,
        5738.4,  3024. ,  5323.6,   894. ,   969.6,   853.6,  3212.4,
        8978. , 15631.4,  1501.8,   741. ,   719. , 13361.8,  5946.2,
        1390.4,   831.8,  3505.4,  1418.4,  6041.4,   817. ,   604.6,
         798.6,   898.4,   702.2,  3239.2,   849.8,   672.2,   933.4,
        8120.8,  2746. ,  1590.6,  2277. , 11342.8, 11014.8, 10340. ,
        5275.2,   920. ,  4036.4,   798.6,  1243.8,   656.8,  1068.2,
         723.6,   798.6,  1020.8,  4863. ,  1020.8,  5685.8,   660. ,
         922.4,   655.6,  1114.8,  3497.2,   725.8,   644.8,  4803.4,
         933.4,  1099.4,   799.4,   747. ,   996.2,  1804.8,  2200. ,
        1736.2,   909. ,   634.6,  1792.4,  3632.8,   644.8,   797.2,
         670.6,   670.6,   662.4,  2013.2,  7856.4,  7693.2,  4123. ,
         632.8,   853.8,  1494.8, 13876.4,  1041.4,  2187.6,   796.6,
        6038. ,   494. ,   830.6, 14303.6,  7656.8,   641.8,  7761.4,
        5924.6,  4407.2,   939.4,   600.8,  3169. ,  4322.6,   853. ,
        4587.8,   747. ,  3364.2,   494. ,   845.4,   640.8, 15588.4,
        1008. ,  3455. ,  9413.2,   702.2,  1964.2,   607.4,   858. ,
        6805.8,  1102.4,   759. ,  8491.6,   644.6,   516.8,  1052.4,
         687.6,   537. ,  5650.4,   748.4,   587.6,  4850.4,  1478.4,
         918.8,  4258.2,   671.4,   840. ,  1176.4,  1399.6,  2227.8,
         733.4,   832.6,   587.6,  1569.6,  8682.2,   903.2,   954. ,
         829.2,   728.8,  3350.6,  5048.8,   724.6,   582.8,  3920.8,
        5179.2,  4256. ,  8547.2,  4805.6,   623. ,  4571.8,  9656.4,
         585.4,   576.8, 13249.8,  2385. ,  1988.2,  4377.6,  1953. ,
        1125.4,  4497.8,  3687.2,  3672.6,  3045.6,  1330.2,   570.4,
        5182.4,  1273.8,   625.6,   742.2,   773. ,  3863.4,   682.2,
         955.6,  4341.2,  4996.6,  2695.4,  1948.8,   914.4,   794.4,
        8279.8,   779.4,  1083.4, 13696. ,   747.8,   952.8,  4906.4,
        3778.2,   704.4,  3862. ,  7086.8,   644.8,   642.6,   736.2,
        1550.2, 12611.6,   770.6])

In [42]:
# find k nearest indices

k = 5
d = np.sqrt(np.sum((X_train_arr - X_test_arr[0])**2, axis=1))  # distances for test row 0
nearest_k_index = np.argpartition(d, k-1)[:k]
nearest_k_index

array([36877, 19489, 39686,  6604, 39485], dtype=int64)

In [43]:
d
d.shape

array([5.04089074, 4.94278173, 4.40460914, ..., 4.16962464, 3.22527479,
       4.40553675])

(40345,)

### Step 7: Model Evaluation

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [45]:
# Make y_test_small to match 500 predictions

y_test_small = y_test.iloc[:500]   # because you predicted only 500 rows
y_test_small

43657     1435
4274      3584
47412     1851
44437     1590
13975     5690
         ...
29348      698
31059      752
53668     2709
23467    11463
46108     1743
Name: price, Length: 500, dtype: int64

In [50]:
mae = mean_absolute_error(y_test_small, y_pred_scratch)

mse = mean_squared_error(y_test_small, y_pred_scratch)

rmse = np.sqrt(mse)

r2 = r2_score(y_test_small, y_pred_scratch)

print("Scratch KNN Evaluation (500 test rows)")
print("MAE  :", mae)
print("RMSE :", rmse)
print("R2_Score :", r2)

Scratch KNN Evaluation (500 test rows)
MAE  : 1077.7188
RMSE : 1845.1697336993147
R2_Score : 0.7697687809375005

### Step 8: Train Sklearn KNN and compare

In [47]:
from sklearn.neighbors import KNeighborsRegressor

k = 5
knn_model = KNeighborsRegressor(n_neighbors=k)   # default distance = Euclidean

knn_model.fit(X_train_small, y_train_small)

KNeighborsRegressor()

In [48]:
# Predict on the same small test

y_pred_sklearn = knn_model.predict(X_test_small)
y_pred_sklearn[:10]

array([4437.4, 2087.2, 1237.2, 1128.6, 4756.8,  597.4,  675.6, 1330.6,
       1186. , 4098. ])

In [51]:
# Evaluate sklearn KNN on same 500 test rows

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_sk = mean_absolute_error(y_test_small, y_pred_sklearn)
mse_sk = mean_squared_error(y_test_small, y_pred_sklearn)
rmse_sk = np.sqrt(mse_sk)
r2_sk = r2_score(y_test_small, y_pred_sklearn)

print("Sklearn KNN Evaluation (500 test rows)")
print("MAE  :", mae_sk)
print("RMSE :", rmse_sk)
print("R2_score  :", r2_sk)

Sklearn KNN Evaluation (500 test rows)
MAE  : 1077.6516000000001
RMSE : 1845.1262848271388
R2_score  : 0.7697796234836898

In [53]:
# Comparing scratch vs sklearn

print("---- Comparison (Scratch vs Sklearn) ----")
print("MAE  :", mae, "vs", mae_sk)
print("RMSE :", rmse, "vs", rmse_sk)
print("R2_Score:", r2, "vs", r2_sk)

---- Comparison (Scratch vs Sklearn) ----
MAE  : 1077.7188 vs 1077.6516000000001
RMSE : 1845.1697336993147 vs 1845.1262848271388
R2_Score: 0.7697687809375005 vs 0.7697796234836898

## Observations from Scratch Operation of KNN vs Using kNN from SKlearn
- Scratch KNN and sklearn `KNeighborsRegressor` produced exactly the same MAE, RMSE, and R² for `k = 5`, which confirms the scratch implementation matches sklearn’s behavior.
- This is expected because sklearn KNN regression (with default `weights='uniform'`) predicts by taking the average of the target values of the k nearest neighbors — same logic used in the scratch code.
- Any differences usually come from changing distance metric/weights (like `weights='distance'`) or using different preprocessing.